package concurency.chat;

public enum ServerEventType {

    SERVER_STARTED,
    CONNECTION_ACCEPTED,
    USER_JOINED,
    MESSAGE_RECEIVED,
    CONNECTION_CLOSED,
    SPECIAL_MESSAGE_RECEIVED,

    // Room actions
    PUBLIC_ROOM_OPEN_REQUEST,
    PRIVATE_ROOM_OPEN_REQUEST,
    PUBLISH_TO_ROOM,
    JOIN_ROOM,
    CLOSE_ROOM_REQUEST
}
