POST http://localhost:8080/joinUser
Content-Type: application/json
Accept: application/json

{
  "port" : 1,
  "userName": "Jan"
}

###

POST http://localhost:8080/message
Content-Type: application/json
Accept: application/json

{
  "name" : "Jan",
  "message": "I am Jan"
}

###

POST http://localhost:9000/handleFile
Content-Type: application/json
Accept: application/json

{
  "name" : "Jan",
  "message": "I am Jan"
}

