package concurency.chat.server;

public enum ServerEventType {

    SERVER_STARTED,
    CONNECTION_ACCEPTED,
    SPECIAL_MESSAGE_RECEIVED_UNHANDLED,
    SPECIAL_MESSAGE_RECEIVED_HANDLED,
    USER_JOINED,
    USER_LEFT_CHAT,
    MESSAGE_RECEIVED,
    CONNECTION_CLOSED,
    SPECIAL_MESSAGE_RECEIVED,

    // Room actions
    PUBLIC_ROOM_OPEN_REQUEST,
    PRIVATE_ROOM_OPEN_REQUEST,
    PUBLISH_TO_ROOM_REQUEST,
    JOIN_ROOM_REQUEST,
    ADD_USER_TO_ROOM_REQUEST,
    CLOSE_ROOM_REQUEST,

    PRIVATE_ROOM_OPENED,
    PUBLIC_ROOM_OPENED,

    // File transfer actions

    SEND_FILE_REQUEST,
    ACCEPT_FILE,

    LOG_WRITE_MESSAGE,
    READ_HISTORY_REQUEST
}
